# Generated by Django 3.2.5 on 2021-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('JobTitre', models.CharField(max_length=1000)),
                ('Secteur', models.CharField(max_length=1000)),
                ('nbCandidat', models.CharField(max_length=1000)),
                ('DureeAttente', models.CharField(max_length=1000)),
                ('StatusOffre', models.CharField(max_length=1000)),
                ('Entreprise', models.CharField(max_length=1000)),
                ('Lieu', models.CharField(max_length=1000)),
                ('Taille', models.CharField(max_length=100)),
                ('Mission', models.TextField('type mission')),
                ('TypeRecrutement', models.CharField(max_length=1000)),
                ('CompTechnique', models.TextField('competence tech')),
                ('CompHumaine', models.TextField('competence hum')),
                ('Profile', models.TextField('profile type')),
            ],
        ),
    ]
