# Generated by Django 3.2.5 on 2021-07-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='CompHumaine',
            field=models.TextField(verbose_name='competence hum'),
        ),
        migrations.AlterField(
            model_name='infos',
            name='CompTechnique',
            field=models.TextField(verbose_name='competence tech'),
        ),
        migrations.AlterField(
            model_name='infos',
            name='Mission',
            field=models.TextField(verbose_name='type mission'),
        ),
        migrations.AlterField(
            model_name='infos',
            name='Profile',
            field=models.TextField(verbose_name='profile type'),
        ),
    ]
