# Generated by Django 3.2.5 on 2021-07-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210721_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='Taille',
            field=models.CharField(max_length=100),
        ),
    ]
