# Generated by Django 3.2.5 on 2021-07-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_infos_taille'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('JobTitre', models.CharField(max_length=1000)),
                ('Secteur', models.CharField(max_length=1000)),
                ('nbCandidat', models.CharField(max_length=1000)),
                ('DureeAttente', models.CharField(max_length=1000)),
                ('StatusOffre', models.CharField(max_length=1000)),
                ('Entreprise', models.CharField(max_length=1000)),
                ('Lieu', models.CharField(max_length=1000)),
                ('Taille', models.CharField(max_length=100)),
                ('Mission', models.TextField(verbose_name='type mission')),
                ('Propos', models.TextField(verbose_name='a propos')),
                ('TypeRecrutement', models.CharField(max_length=1000)),
                ('CompTechnique', models.TextField(verbose_name='competence tech')),
                ('CompHumaine', models.TextField(verbose_name='competence hum')),
                ('Profile', models.TextField(verbose_name='profile type')),
                ('Experience', models.TextField(verbose_name='experience')),
                ('Diplome', models.TextField(verbose_name='diplome')),
            ],
        ),
        migrations.AddField(
            model_name='infos',
            name='Propos',
            field=models.TextField(null=True, verbose_name='a propos'),
        ),
    ]
