# Generated by Django 3.2.5 on 2021-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210721_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos1',
            name='lang',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
