# Generated by Django 3.2.5 on 2021-07-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_infos1_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos1',
            name='plateform',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
